// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: service.proto

package pb

import (
	context "context"
	fmt "fmt"
	_ "github.com/gogo/googleapis/google/api"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "github.com/mwitkow/go-proto-validators"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

func init() { proto.RegisterFile("service.proto", fileDescriptor_a0b84a42fa06f626) }

var fileDescriptor_a0b84a42fa06f626 = []byte{
	// 278 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x8f, 0xbf, 0x4a, 0x34, 0x31,
	0x14, 0xc5, 0xc9, 0xf2, 0x7d, 0xab, 0x8c, 0xac, 0xae, 0xb1, 0x5b, 0x64, 0x8a, 0x2d, 0xc5, 0x99,
	0x80, 0x82, 0x85, 0x60, 0xe1, 0x36, 0x36, 0x56, 0x82, 0x0f, 0x90, 0x19, 0xaf, 0x77, 0x83, 0x33,
	0xb9, 0x31, 0x37, 0xb3, 0xd3, 0xdb, 0x59, 0xfb, 0x12, 0x3e, 0x8a, 0xa5, 0xe0, 0x0b, 0xc8, 0xe0,
	0x83, 0xc8, 0xc4, 0xf1, 0x1f, 0x58, 0xe5, 0x9c, 0x93, 0xdf, 0x39, 0x24, 0xc9, 0x84, 0xc1, 0xaf,
	0x4c, 0x09, 0xb9, 0xf3, 0x14, 0x48, 0x8e, 0x5c, 0x31, 0xdb, 0x45, 0x22, 0xac, 0x40, 0x69, 0x67,
	0x94, 0xb6, 0x96, 0x82, 0x0e, 0x86, 0x2c, 0x7f, 0x10, 0xb3, 0xfd, 0x78, 0x94, 0x19, 0x82, 0xcd,
	0xb8, 0xd5, 0x88, 0xe0, 0x15, 0xb9, 0x48, 0xfc, 0x41, 0x67, 0x68, 0xc2, 0xb2, 0x29, 0xf2, 0x92,
	0x6a, 0x85, 0x84, 0xa4, 0x62, 0x5c, 0x34, 0xd7, 0xd1, 0x45, 0x13, 0xd5, 0x80, 0x1f, 0xfd, 0xc0,
	0xeb, 0xd6, 0x84, 0x1b, 0x6a, 0x15, 0x52, 0x16, 0x2f, 0xb3, 0x95, 0xae, 0xcc, 0x95, 0x0e, 0xe4,
	0x59, 0x7d, 0xc9, 0xa1, 0x37, 0xa9, 0x81, 0x59, 0xe3, 0xf0, 0x8b, 0x83, 0x7b, 0x91, 0xfc, 0x3b,
	0x6d, 0xc2, 0x52, 0x9e, 0x24, 0xff, 0xcf, 0x09, 0x8d, 0x95, 0x5b, 0xb9, 0x2b, 0xf2, 0x4b, 0x06,
	0x7f, 0x01, 0xb7, 0x0d, 0x70, 0x98, 0x4d, 0xbf, 0x03, 0x76, 0x64, 0x19, 0xe6, 0xdb, 0x77, 0x2f,
	0x6f, 0x0f, 0xa3, 0x8d, 0xf9, 0x58, 0x55, 0x7d, 0xe5, 0x58, 0xec, 0xc9, 0x45, 0xb2, 0x76, 0x06,
	0xa1, 0xa7, 0xa4, 0xec, 0xf9, 0xc1, 0x7c, 0x6e, 0xec, 0xfc, 0xca, 0x86, 0x99, 0xcd, 0x38, 0xb3,
	0x2e, 0xc7, 0xaa, 0x61, 0xf0, 0xbc, 0x98, 0x3e, 0x76, 0xa9, 0x78, 0xea, 0x52, 0xf1, 0xdc, 0xa5,
	0xe2, 0xb5, 0x4b, 0x45, 0x31, 0x8e, 0x8f, 0x3c, 0x7c, 0x0f, 0x00, 0x00, 0xff, 0xff, 0xc5, 0x3e,
	0x2b, 0x98, 0x7b, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AuthClient is the client API for Auth service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthClient interface {
	Login(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*UserResponse, error)
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error)
}

type authClient struct {
	cc *grpc.ClientConn
}

func NewAuthClient(cc *grpc.ClientConn) AuthClient {
	return &authClient{cc}
}

func (c *authClient) Login(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*UserResponse, error) {
	out := new(UserResponse)
	err := c.cc.Invoke(ctx, "/pb.Auth/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error) {
	out := new(GetUserResponse)
	err := c.cc.Invoke(ctx, "/pb.Auth/GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServer is the server API for Auth service.
type AuthServer interface {
	Login(context.Context, *UserRequest) (*UserResponse, error)
	GetUser(context.Context, *GetUserRequest) (*GetUserResponse, error)
}

// UnimplementedAuthServer can be embedded to have forward compatible implementations.
type UnimplementedAuthServer struct {
}

func (*UnimplementedAuthServer) Login(ctx context.Context, req *UserRequest) (*UserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (*UnimplementedAuthServer) GetUser(ctx context.Context, req *GetUserRequest) (*GetUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUser not implemented")
}

func RegisterAuthServer(s *grpc.Server, srv AuthServer) {
	s.RegisterService(&_Auth_serviceDesc, srv)
}

func _Auth_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Auth/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).Login(ctx, req.(*UserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Auth/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).GetUser(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Auth_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Auth",
	HandlerType: (*AuthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _Auth_Login_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _Auth_GetUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
